### ISSUE TITLE
Publish ServiceProvider not working

### ISSUE THREAD

**Issue by wprk** [SoftNWeb/laravel-coming-soon#3]
Getting an error of `Class 'softnweb\laravel-coming-soon\ComingSoonServiceProvider' not found` when trying to use this package.

Solved it in my own project by adding the following to my own /composer.json file:
```
    "extra": {
        "laravel": {
            "dont-discover": [
                "softnweb/laravel-coming-soon"
            ]
        }
    }
```
```
    "autoload": {
        "psr-4": {
            "snw\\ComingSoon\\": "vendor\\softnweb\\laravel-coming-soon\\"
        }
    }
```

And also manually adding the ServiceProvider to my `/config/app.php`

Not sure how to get it to work properly so unable to create a PR

**Comment by SoftNWeb** [comment]
Thanks. We will upload a fix soon.

**Comment by ominfowave** [comment]
In app.php line 178:

  Undefined constant 'softnweb\laravel'

**Comment by SoftNWeb** [comment]
Fixed https://github.com/SoftNWeb/laravel-coming-soon/commit/eef6242726b562d7bb9c13f069345980c3477aac
